#--- Install node dependencies 
FROM node:16.17.0-alpine as build
RUN echo "--- Install node dependencies  ---"
WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . /app
RUN npm run build
RUN echo "--- build ---"
FROM nginx:1.21-alpine-perl
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY  nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]