#--- Install node dependencies 
FROM node:16.17.0-alpine as build
RUN echo "--- Install node dependencies  ---"
WORKDIR /app
COPY package.json ./
RUN npm install 
COPY . /app
RUN npm run build
RUN echo "--- build ---"
FROM nginx:1.21-alpine-perl
COPY --from=build /app/dist/ /usr/share/nginx/html

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]