#--- Install node dependencies 
FROM node:16.17.0-alpine 
RUN echo "--- Install node dependencies  ---"
WORKDIR /app
COPY package*.json ./
RUN npm install 
# RUN npm install -g npm@8.19.2
COPY . /app
EXPOSE 3000
CMD ["npm", "run", "serve"]
