version: '3.7'
services:
    web:
     build: ./frontend
     ports:
      - 3000:8080
    api:
     build: ./backend
     ports:
      - 3333:3333
     environment:
      POSTGRESQL_URL: "postgres://postgres:123@db"

    db:
     image: supabase/postgres:14.1.0
     environment:
      POSTGRES_PASSWORD: 123
 
     volumes:
      - /var/lib/postgresql/data

    
     


